name: Print Repository URL

on: [push]

jobs:
  print-repo-url:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Repository URL
      run: python main.py "https://github.com/${{ github.repository }}"
